/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-container": "#5a6375",
                "surface-bright": "#f7f9fc",
                "primary": "#000a1e",
                "on-tertiary-fixed": "#341100",
                "tertiary-fixed": "#ffdbcb",
                "tertiary": "#180500",
                "on-surface": "#191c1e",
                "secondary": "#565f70",
                "surface-dim": "#d8dadd",
                "primary-fixed": "#d6e3ff",
                "background": "#f7f9fc",
                "surface-container": "#eceef1",
                "surface-container-highest": "#e0e3e6",
                "on-secondary-fixed": "#131c2b",
                "primary-container": "#002147",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "on-tertiary-fixed-variant": "#6c391d",
                "primary-fixed-dim": "#aec7f6",
                "on-primary-fixed": "#001b3d",
                "surface-tint": "#465f88",
                "secondary-fixed": "#dae3f8",
                "error": "#ba1a1a",
                "surface-container-high": "#e6e8eb",
                "surface-container-low": "#f2f4f7",
                "outline": "#74777f",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#2d476f",
                "on-surface-variant": "#44474e",
                "tertiary-fixed-dim": "#ffb691",
                "surface-variant": "#e0e3e6",
                "error-container": "#ffdad6",
                "inverse-primary": "#aec7f6",
                "surface": "#f7f9fc",
                "tertiary-container": "#3d1500",
                "on-background": "#191c1e",
                "on-secondary-fixed-variant": "#3e4758",
                "on-error-container": "#93000a",
                "inverse-surface": "#2d3133",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#bec7db",
                "inverse-on-surface": "#eff1f4",
                "secondary-container": "#d7e0f5",
                "outline-variant": "#c4c6cf",
                "on-primary-container": "#708ab5",
                "on-tertiary-container": "#b97958"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
